# Generated by Django 6.0.6 on 2026-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hiti_study_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='admission_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='reminder_days_before',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='student_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='student_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
