# Generated by Django 6.0.6 on 2026-06-07 04:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage_resolved_at_contactmessage_staff_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='admission_number',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=12),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='student_photo',
            field=models.FileField(blank=True, upload_to='student_photos/'),
        ),
    ]
