# Generated by Django 6.0.6 on 2026-06-07 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_seatbooking_admission_number_seatbooking_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryprofile',
            name='helpline_phone',
            field=models.CharField(blank=True, default='08429395336', max_length=30),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='owner_name',
            field=models.CharField(default='Sumit Kumar Patel', max_length=120),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='owner_photo',
            field=models.FileField(blank=True, upload_to='owner_photos/'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='payment_qr',
            field=models.FileField(blank=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='support_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='support_phone',
            field=models.CharField(blank=True, default='08429395336', max_length=30),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_seat_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_proof',
            field=models.FileField(blank=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='active', max_length=12),
        ),
    ]
